# .bashrc

# Change according to your MassTransferFoam installation directory
MTFOAM_DIR=$HOME/massTransferFoam
MTFOAM_SRC=$MTFOAM_DIR/src
MTFOAM_APPBIN=$MTFOAM_DIR/bin
MTFOAM_LIBBIN=$MTFOAM_DIR/lib
MTFOAM_TUTORIALS=$MTFOAM_DIR/tutorials
MTFOAM_IMG=$MTFOAM_DIR/images
MTFOAM_RUNS=$MTFOAM_DIR/runs

# Change according to your openfoam installation directory
#export FOAM_INST_DIR=/usr/lib/openfoam
export FOAM_INST_DIR=$HOME/OpenFOAM
source $HOME/OpenFOAM/OpenFOAM-v2406/etc/bashrc
#source /usr/lib/openfoam/openfoam2212/etc/bashrc
#export FOAM_INST_DIR=$HOME/OpenFOAM
#source $HOME/OpenFOAM/OpenFOAM-v2106/etc/bashrc
#export FOAM_INST_DIR=/opt/OpenFOAM
#source /opt/OpenFOAM/OpenFOAM-v2106/etc/bashrc

export MTFOAM_DIR
export MTFOAM_SRC
export MTFOAM_APPBIN
export MTFOAM_LIBBIN
export MTFOAM_TUTORIALS
export MTFOAM_IMG
export MTFOAM_RUNS

alias run='cd $MTFOAM_RUNS'


export PATH=$PATH:$MTFOAM_APPBIN
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MTFOAM_LIBBIN

export PATH=$PATH:$MPI_ARCH_PATH/include

#Third party software
#source $MTFOAM_DIR/ThirdParty/bashrc

alias dir='cd $MTFOAM_DIR'
alias src='cd $MTFOAM_DIR/src'
alias app='cd $MTFOAM_DIR/applications'
alias tut='cd $MTFOAM_DIR/tutorials'

echo "Welcome to MassTransferFoam!"

